apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: noop
spec:
  steps:
    - name: noop
      image: opensuse/leap
      command:
        - echo
      args:
        - "This task doesn't really do anything but that's cool!"
        