apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-pr-pipeline
spec:
  params:
  - name: repo-url
    type: string
  - name: commit-id
    type: string
  workspaces:
  - name: shared-data
    description: This is where the cloned repo will be put
  tasks:
    - name: clone-repo
      taskRef: 
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.commit-id)
