apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - name: namespace
      description: The namespace to deploy to
      type: string
      default: "default"
  steps:
    - name: apply
      image: bitnami/kubectl:1.19.10
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          kubectl apply -n $(inputs.params.namespace) -f $(inputs.params.manifest_dir)
