apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision (SHA)
    - name: gitrepositoryurl
      description: The git repository url ("https://github.com/foo/bar.git")
    - name: imagename
      description: The name of the image we're building
      default: timirnich/shoppinglist-redis
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-pr-pipeline-run-
      spec:
        pipelineRef:
          name: github-pr-pipeline
        serviceAccountName: build-bot
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 500Mi
        params:
        - name: repo-url
          value: $(tt.params.gitrepositoryurl)
        - name: commit-id
          value: $(tt.params.gitrevision) 
        - name: image-name
          value: $(tt.params.imagename)
        - name: path-to-image-context
          value: .
        - name: path-to-dockerfile
          value: /workspace/source/Dockerfile