apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-pr-pipeline
spec:
  params:
  - name: repo-url
    type: string
  - name: commit-id
    type: string
  - name: image-name
    type: string
  - name: path-to-image-context
    type: string
  - name: path-to-dockerfile
    type: string
  workspaces:
  - name: shared-data
    description: This is where the cloned repo will be put
  tasks:
    - name: clone-repo
      taskRef: 
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.commit-id)
    - name: build-image
      taskRef:
        name: kaniko
      runAfter: 
        - clone-repo
      params:
      - name: IMAGE
        value: $(params.image-name)
      - name: CONTEXT
        value: $(params.path-to-image-context)
      - name: DOCKERFILE
        value: $(params.path-to-dockerfile)
      workspaces:
      - name: source
        workspace: shared-data
